[project]
name = "gtpost"
version = "0.1.0"
description = "Delft3D GeoTool code"
authors = ["Erik van Onselen <erik.vanonselen@deltares.nl>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "linux-aarch64", "osx-64", "osx-arm64"]

[tasks]
test = "python -m pytest --verbose --cov=gtpost --cov-config=.coveragerc"
docs = "sphinx-build -b html docs ./docs/build"
format = "black ."
lint = "ruff check --fix ./gtpost"

[dependencies]
python = "3.11.*"
numpy = ">=1.26.4,<1.27"
numba = "*"
pandas = ">=2.0.1"
rasterio = "*"
xarray = "*"
matplotlib = "*"
scikit-image = "*"
shapely = ">=2.0.1"
h5netcdf = "*"
mako = "*"
pyvista = "*"
black = "*"
pytest = "*"
pytest-cov = "*"
ruff = "*"
sphinx = "*"
sphinx-rtd-theme = "*"
pip = ">=24.0,<25"
psutil = ">=6.1.0,<7"


[pypi-dependencies]
gtpost = { path = ".", editable = true }

[system-requirements]
linux = "5.4"
