[project]
name = "gtpost"
version = "0.1.0"
description = "Delft3D GeoTool code"
authors = ["Erik van Onselen <erik.vanonselen@deltares.nl>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]
install = "python -m pip install --no-deps --editable ."
test = { depends_on = [
    "install",
], cmd = "python -m pytest --verbose --cov=gtpost --cov-config=.coveragerc" }
docs = "sphinx-build -b html docs ./docs/build"
format = "black ."
lint = "ruff check --fix ./gtpost"

[dependencies]
python = "3.12.*"
numpy = ">=1.22.3,<2.1"
numba = "*"
pandas = ">=2.2.3,<3"
pillow = ">=10.4.0,<11"
tqdm = ">=4.66.5,<5"
requests = ">=2.32.3,<3"
ultralytics = ">=8.2.34,<9"
imgviz = ">=0.11.1,<0.12"
labelme = ">=5.2.1,<6"
pyqt = ">=5.15.9,<6"
pycocotools = ">=2.0.8,<3"
nomkl = ">=1.0,<2"
rasterio = "*"
xarray = "*"
matplotlib = "*"
scikit-image = "*"
shapely = ">=2.0.1"
h5netcdf = "*"
mako = "*"
pyvista = "*"
black = "*"
pytest = "*"
pytest-cov = "*"
ruff = "*"
sphinx = "*"
sphinx-rtd-theme = "*"
pip = ">=24.0,<25"

[pypi-dependencies]
labelme2yolo = ">=0.2.5, <0.3"
torch = ">=2.2.2, <3"
torchvision = ">=0.19.1, <0.20"

