[project]
name = "gtpost"
version = "0.1.0"
description = "Delft3D GeoTool code"
authors = ["Erik van Onselen <erik.vanonselen@deltares.nl>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]
test = "python -m pytest --verbose --cov=gtpost --cov-config=.coveragerc"
docs = "sphinx-build -b html docs ./docs/build"
format = "black ."
lint = "ruff check --fix ./gtpost"

[dependencies]
python = "3.12.*"
numpy = "*"
numba = "*"
pandas = "*"
pillow = "*"
tqdm = "*"
requests = "*"
imgviz = "*"
labelme = "*"
pyqt = "*"
pycocotools = "*"
nomkl = "*"
rasterio = "*"
xarray = "*"
matplotlib = "*"
scikit-image = "*"
shapely = ">=2.0.1"
h5netcdf = "*"
mako = "*"
pyvista = "*"
black = "*"
pytest = "*"
pytest-cov = "*"
ruff = "*"
sphinx = "*"
sphinx-rtd-theme = "*"
pip = "*"
cuda-toolkit = "*"
psutil = "*"

[pypi-dependencies]
labelme2yolo = "*"
torch = "*"
torchvision = "*"
ultralytics = "*"
gtpost = { path = ".", editable = true }

[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu121"]

[system-requirements]
cuda = "12.1"

