name: Ribasim Python Tests
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
     types: [
      opened,
      edited,
      synchronize
      ]
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Python ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        cache: false
        pixi-version: "latest"
    - name: Test
      run: pixi run test
