on:
 release:
   types: [created]

name: Publish image to registry

jobs:
    build-and-publish-release:
        name: Build and publish container
        uses: ./.github/workflows/build-and-publish.yml
        with:
          Registry: ghcr.io
          ImageName: ${{ github.repository }}
          Tag: ${{ github.event.release.tag_name }}
          WorkingDir: .
        secrets: inherit